### ISSUE TITLE
validate_file checks return false on windows local WAMP/XAMPP setup

### ISSUE THREAD

**Issue by roborovski** [johnbillion/extended-template-parts#1]
`validate_file` returns false when checking absolute paths on windows (since they have colons in them), so no template part is returned. 

Seems like it's a pretty common thing e.g. https://github.com/Automattic/amp-wp/pull/295

**Comment by johnbillion** [comment]
Yikes. Could you file a ticket on core.trac.wordpress.org for this too please?

**Comment by johnbillion** [comment]
This needs to be addressed in core. See https://core.trac.wordpress.org/ticket/41736.
