### ISSUE TITLE
Add hook after outputting a template

### ISSUE THREAD

**Issue by JacobDB** [johnbillion/extended-template-parts#14]
I've been using a `$post` variable in my template parts for yeras, thinking that they where self-encapsulated, but I just ran in to an issue and discovered this is not the case. It was my fault for making this assumption, but I've found a simple solution for my use case: after a template, I can call `wp_reset_postdata()` to get things back to normal. Ideally, I'd like to run this automatically after any template is called, but there doesn't appear to be a hook available do that.

**Comment by johnbillion** [comment]
Thanks for the comment.

I can see the use case here, but to be honest there's a good chance that you'll run into the opposite issue if you automatically call `wp_reset_postdata()` after template parts, particularly when you're inside a loop. You may inadvertently reset the post in a loop.

It's best to _explicitly_ call this function so it's clear to anyone reading the code that it is being called.

**Comment by JacobDB** [comment]
Very good point, you're absolutely right. Thanks.
