### ISSUE TITLE
Support to PHP 8

### ISSUE THREAD

**Issue by zsheaib** [johnbillion/extended-template-parts#17]
We are having issues with the library when we update the php version to 8.0

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires johnbillion/extended-template-parts ^2.1.0 -> satisfiable by johnbillion/extended-template-parts[2.1.0].
    - johnbillion/extended-template-parts 2.1.0 requires php ^7.0

Will you release a version supporting php 8.0?

**Comment by johnbillion** [comment]
Fixed in 95bec9cd6428cb73ac626f01a42d866086da16bd 👍
