### ISSUE TITLE
Absolute Windows drive paths are not allowed

### ISSUE THREAD

**Issue by matthewdorman** [johnbillion/extended-template-parts#3]
I hit an issue deploying to a Windows environment, where it wasn't returning any template output. I tracked it down to the use of the `validat_file` core function. For me, I simply allowed the return of 2 or 0 and it's working fine.

I updated these two lines (happy to put in a PR if you think this is a valid issue):
https://github.com/johnbillion/extended-template-parts/blob/master/extended-template-parts.php#L160
https://github.com/johnbillion/extended-template-parts/blob/master/extended-template-parts.php#L149

**Comment by johnbillion** [comment]
Thanks for the report. This is a known problem in WordPress core and I don't think it's something that I should start messing around with in this library. Unless you think differently?

See #1.
