### ISSUE TITLE
Maybe typo in Readme

### ISSUE THREAD

**Issue by ibes** [johnbillion/extended-template-parts#5]
Hi, the readme says:

> Extended **CPT**s is a library which provides extended functionality to WordPress template parts, including template variables and caching.

CPT = Custom Post Types?!

Should that be "Extended Template Parts" or "Extended TPs"?

**Comment by ibes** [comment]
https://github.com/johnbillion/extended-template-parts/pull/6

**Comment by johnbillion** [comment]
Thanks!
