### ISSUE TITLE
Allow template part markup to be cached separately when template vars differ 

### ISSUE THREAD

**Issue by goldenapples** [johnbillion/extended-template-parts#9]
I would have expected separate `get_extended_template_part` calls to the same template part, but with different template vars, to be cached separately. Instead, it looks like the cache key used to cache output is built only from the template location and the `$args` array.

As a result, this kind of usage:

```
while ( have_posts() ) :
    get_extended_template_part(
        'post-card',
        '',
        [ 'post_id' => get_the_ID() ],
        [ 'cache' => HOUR_IN_SECONDS ]
    );
endwhile;
```

will just output the same post each time rather than building the markup for each one, and caching them for future runs.

Using the `$vars` object in building the cache key would get around this problem.

**Comment by johnbillion** [comment]
Good catch, yep `$this->vars` should also be used in the key construction in the `cache_key()` method.
